## setup

In [1]:
# import stuff
from pathlib import Path
import pandas as pd

In [2]:
# load data from folder
folder = Path('../data/processed')

# non-outlier datasets
listings_clean = pd.read_csv(folder / 'wk7_listings_clean.csv', low_memory = False)
sold_clean = pd.read_csv(folder / 'wk7_sold_clean.csv', low_memory = False)

print('Listings shape (clean):', listings_clean.shape)
print('Sold shape (clean):', sold_clean.shape)

# flagged-outlier datasets
listings_flagged = pd.read_csv(folder / 'wk7_listings_flagged.csv', low_memory = False)
sold_flagged = pd.read_csv(folder / 'wk7_sold_flagged.csv', low_memory = False)

print('Listings shape (flagged):', listings_flagged.shape)
print('Sold shape (flagged):', sold_flagged.shape)

Listings shape (clean): (171148, 46)
Sold shape (clean): (465483, 55)
Listings shape (flagged): (653323, 47)
Sold shape (flagged): (480134, 56)

In [3]:
stats_cols = [
    'City',
    'ClosePrice',
    'DaysOnMarket',
    'price_per_sqft',
    'close_to_original_list_ratio',
    'ListOfficeName',
    'ListAgentFullName'
]

## check sold dataset

### clean

In [4]:
sold_clean_mp = sold_clean[sold_clean['City'] == 'Milpitas']

print('Milpitas sold shape (clean):', sold_clean_mp.shape)
sold_clean_mp[stats_cols].head()

Milpitas sold shape (clean): (699, 55)

,City,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio,ListOfficeName,ListAgentFullName
412,Milpitas,1481000.0,4.0,969.240838,1.176330,Keller Williams Palo Alto,David Wang
465,Milpitas,1615088.0,5.0,857.720659,1.076726,168 Realty,Erica Wong
601,Milpitas,1400000.0,2.0,922.874094,1.000000,"JDK & Associates Realty, Inc.",Terry Oliverio-Ketchel
1018,Milpitas,1130000.0,0.0,858.662614,1.000886,Coldwell Banker Realty,Carol Zhang
1265,Milpitas,835000.0,20.0,663.224782,0.994048,"Nihow Real Estate, Inc.",Jason Huang

In [5]:
sold_clean_mp[stats_cols].describe()

,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio
count,6.990000e+02,699.000000,699.000000,699.000000
mean,1.417408e+06,19.816881,890.839461,1.034062
std,5.123682e+05,23.328677,202.449704,0.075383
min,4.000000e+05,0.000000,398.489933,0.764277
25%,1.120000e+06,7.000000,739.078634,0.988410
50%,1.360000e+06,12.000000,842.799771,1.027778
75%,1.632110e+06,22.000000,1011.238652,1.081710
max,4.300000e+06,186.000000,1707.779886,1.212121

In [6]:
sold_clean_mp.groupby('year')['ClosePrice'].median()

year
2024.0    1385000.0
2025.0    1372500.0
2026.0    1265000.0
Name: ClosePrice, dtype: float64

In [7]:
sold_clean_mp.groupby('year')['DaysOnMarket'].mean()

year
2024.0    17.981530
2025.0    19.715116
2026.0    28.250000
Name: DaysOnMarket, dtype: float64

In [8]:
sold_clean_mp.groupby('year')['close_to_original_list_ratio'].mean()

year
2024.0    1.049716
2025.0    1.028226
2026.0    1.002843
Name: close_to_original_list_ratio, dtype: float64

In [9]:
sold_clean_mp.groupby('year')['ListingKey'].nunique()

year
2024.0    378
2025.0    172
2026.0    128
Name: ListingKey, dtype: int64

In [10]:
sold_clean_mp.groupby('year')['ClosePrice'].sum()

year
2024.0    538503781.0
2025.0    251401258.0
2026.0    172463040.0
Name: ClosePrice, dtype: float64

In [11]:
sold_clean_mp['ListAgentFullName'].value_counts()

ListAgentFullName
Erica Wong               67
Debbie I. Giordano       24
Sophie Shen              23
David Azimi              13
Kashif Husain            12
                         ..
Megan Miller              1
 Thao Dang & Brian Ng     1
Joe Prather               1
Nguyen Le                 1
Anthony Chen              1
Name: count, Length: 443, dtype: int64

In [12]:
sold_clean_mp['ListOfficeName'].value_counts()

ListOfficeName
Intero Real Estate Services    74
168 Realty                     67
Coldwell Banker Realty         64
Compass                        57
Keller Williams Thrive         34
                               ..
Tuscana Properties              1
Legacy Living Realty            1
Starriver Inc                   1
Joanna Zheng, Broker            1
Keller Williams Silicon         1
Name: count, Length: 188, dtype: int64

In [13]:
sold_clean_mp.groupby('ListOfficeName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListOfficeName
Intero Real Estate Services    112607363.0
Coldwell Banker Realty          89212578.0
168 Realty                      85428520.0
Compass                         84880276.0
Keller Williams Thrive          46120139.0
Name: ClosePrice, dtype: float64

In [41]:
sold_clean_mp.groupby('ListAgentFullName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListAgentFullName
Erica Wong            85428520.0
Debbie I. Giordano    40152362.0
Sophie Shen           29988500.0
David Azimi           22615888.0
Kashif Husain         18775397.0
Name: ClosePrice, dtype: float64

### flagged

In [14]:
sold_flagged_mp = sold_flagged[sold_flagged['City'] == 'Milpitas']

print('Milpitas sold shape (flagged):', sold_flagged_mp.shape)
sold_flagged_mp[stats_cols].head()

Milpitas sold shape (flagged): (734, 56)

,City,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio,ListOfficeName,ListAgentFullName
447,Milpitas,1481000.0,4.0,969.240838,1.176330,Keller Williams Palo Alto,David Wang
501,Milpitas,1615088.0,5.0,857.720659,1.076726,168 Realty,Erica Wong
640,Milpitas,1400000.0,2.0,922.874094,1.000000,"JDK & Associates Realty, Inc.",Terry Oliverio-Ketchel
1069,Milpitas,1130000.0,0.0,858.662614,1.000886,Coldwell Banker Realty,Carol Zhang
1319,Milpitas,835000.0,20.0,663.224782,0.994048,"Nihow Real Estate, Inc.",Jason Huang

In [15]:
sold_flagged_mp[stats_cols].describe()

,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio
count,7.340000e+02,734.000000,734.000000,730.000000
mean,1.429411e+06,19.704360,902.646870,1.043944
std,5.103292e+05,25.010907,213.236485,0.091622
min,4.000000e+05,0.000000,398.489933,0.720752
25%,1.136250e+06,7.000000,742.087645,0.990566
50%,1.370625e+06,12.000000,846.363978,1.034145
75%,1.650000e+06,22.000000,1023.840270,1.094175
max,4.300000e+06,288.000000,1783.681214,1.655185

In [16]:
sold_flagged_mp.groupby('year')['ClosePrice'].median()

year
2024.0    1396497.0
2025.0    1388000.0
2026.0    1260000.0
Name: ClosePrice, dtype: float64

In [17]:
sold_flagged_mp.groupby('year')['DaysOnMarket'].mean()

year
2024.0    17.413366
2025.0    19.630682
2026.0    28.333333
Name: DaysOnMarket, dtype: float64

In [18]:
sold_flagged_mp.groupby('year')['ListingKey'].nunique()

year
2024.0    403
2025.0    176
2026.0    129
Name: ListingKey, dtype: int64

In [19]:
sold_flagged_mp.groupby('year')['ClosePrice'].sum()

year
2024.0    580111899.0
2025.0    259832258.0
2026.0    173688040.0
Name: ClosePrice, dtype: float64

In [20]:
sold_flagged_mp['ListAgentFullName'].value_counts()

ListAgentFullName
Erica Wong            67
Sophie Shen           24
Debbie I. Giordano    24
David Azimi           13
Kashif Husain         12
                      ..
Fe Casem               1
Nelson Nguyen          1
Ramon Concepcion       1
Omar Ruano             1
Anthony Chen           1
Name: count, Length: 463, dtype: int64

In [21]:
sold_flagged_mp['ListOfficeName'].value_counts()

ListOfficeName
Intero Real Estate Services    81
168 Realty                     67
Coldwell Banker Realty         65
Compass                        63
Keller Williams Thrive         35
                               ..
Champion Financial Service      1
North East Realty               1
Miller Service Real Estate      1
Tuscana Properties              1
Keller Williams Silicon         1
Name: count, Length: 192, dtype: int64

In [22]:
sold_flagged_mp.groupby('ListOfficeName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListOfficeName
Intero Real Estate Services    124109471.0
Compass                         95100278.0
Coldwell Banker Realty          90542578.0
168 Realty                      85428520.0
Keller Williams Thrive          47745139.0
Name: ClosePrice, dtype: float64

## check listings dataset

### clean

In [23]:
list_clean_mp = listings_clean[listings_clean['City'] == 'Milpitas']

print('Milpitas listings shape:', list_clean_mp.shape)
list_clean_mp[stats_cols].head()

Milpitas listings shape: (264, 46)

,City,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio,ListOfficeName,ListAgentFullName
950,Milpitas,1505000.0,6.0,1264.705882,1.158584,Everhome,Lindsey Peters
1275,Milpitas,1130000.0,0.0,821.818182,1.076190,Bay Area Home Rebate,Sameer Punjani
1725,Milpitas,1530000.0,2.0,1001.308901,1.094421,Compass,Jerylann Mateo
2877,Milpitas,885000.0,7.0,714.862682,1.068841,Redfin,Joyce Chiu
4053,Milpitas,1810000.0,8.0,1510.851419,1.132666,Rinu Real Estate,Andrew Unyi

In [24]:
list_clean_mp[stats_cols].describe()

,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio
count,2.640000e+02,264.000000,264.000000,264.000000
mean,1.393764e+06,15.503788,895.452510,1.045670
std,4.724268e+05,21.013122,196.995426,0.072271
min,5.000000e+05,0.000000,460.000000,0.838710
25%,1.120000e+06,6.000000,744.363034,1.000000
50%,1.351000e+06,9.000000,851.230691,1.040581
75%,1.615022e+06,18.000000,1009.365984,1.097126
max,4.005000e+06,173.000000,1510.851419,1.204444

In [26]:
list_clean_mp['year'] = pd.to_datetime(list_clean_mp['year_month']).dt.year
list_clean_mp.groupby('year')['ListingKey'].nunique()

C:\Users\User\AppData\Local\Temp\ipykernel_3796\1280378666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  list_clean_mp['year'] = pd.to_datetime(list_clean_mp['year_month']).dt.year

year
2024    116
2025     88
2026     60
Name: ListingKey, dtype: int64

In [27]:
list_clean_mp.groupby('year')['ClosePrice'].sum()

year
2024    167385931.0
2025    123857100.0
2026     76710638.0
Name: ClosePrice, dtype: float64

In [47]:
list_clean_mp.groupby('year')['DaysOnMarket'].mean()

year
2024     8.931034
2025    24.625000
2026    14.833333
Name: DaysOnMarket, dtype: float64

In [48]:
list_clean_mp.groupby('year')['close_to_original_list_ratio'].mean()

year
2024    1.075719
2025    1.026477
2026    1.015724
Name: close_to_original_list_ratio, dtype: float64

In [49]:
list_clean_mp.groupby('year')['ClosePrice'].sum()

year
2024    167385931.0
2025    123857100.0
2026     76710638.0
Name: ClosePrice, dtype: float64

In [46]:
list_clean_mp.groupby('year')['ListingId'].nunique()

year
2024    116
2025     88
2026     60
Name: ListingId, dtype: int64

In [28]:
list_clean_mp['ListAgentFullName'].value_counts()

ListAgentFullName
Erica Wong            31
Sophie Shen           12
Debbie I. Giordano     6
David Azimi            5
Annie Culbertson       5
                      ..
Susan Kuramoto         1
Susan Schall           1
Claire Zhou            1
Alex Urbano Tafoya     1
Julie Charron          1
Name: count, Length: 192, dtype: int64

In [29]:
list_clean_mp.groupby('ListAgentFullName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListAgentFullName
Erica Wong            38689187.0
Sophie Shen           15460500.0
Debbie I. Giordano     8427333.0
David Azimi            7910000.0
Annie Culbertson       7573134.0
Name: ClosePrice, dtype: float64

In [30]:
list_clean_mp['ListOfficeName'].value_counts()

ListOfficeName
Coldwell Banker Realty         34
168 Realty                     31
Intero Real Estate Services    25
Compass                        24
Keller Williams Thrive         15
                               ..
BRG Realty                      1
WR Properties                   1
ALTERA Real Estate              1
Cascade California Realty       1
LPT Realty                      1
Name: count, Length: 88, dtype: int64

In [31]:
list_clean_mp.groupby('ListOfficeName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListOfficeName
Coldwell Banker Realty         44722776.0
Intero Real Estate Services    41242801.0
168 Realty                     38689187.0
Compass                        34407888.0
Keller Williams Thrive         18510500.0
Name: ClosePrice, dtype: float64

### flagged

In [32]:
list_flagged_mp = listings_flagged[listings_flagged['City'] == 'Milpitas']

print('Milpitas listings shape (flagged):', list_flagged_mp.shape)
list_flagged_mp[stats_cols].head()

Milpitas listings shape (flagged): (1152, 47)

,City,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio,ListOfficeName,ListAgentFullName
1382,Milpitas,1505000.0,6.0,1264.705882,1.158584,Everhome,Lindsey Peters
1458,Milpitas,1860000.0,7.0,996.250670,1.241656,The Agency,Ryan Gowdy
1810,Milpitas,1130000.0,0.0,821.818182,1.076190,Bay Area Home Rebate,Sameer Punjani
2428,Milpitas,1530000.0,2.0,1001.308901,1.094421,Compass,Jerylann Mateo
4018,Milpitas,885000.0,7.0,714.862682,1.068841,Redfin,Joyce Chiu

In [33]:
list_flagged_mp[stats_cols].describe()

,ClosePrice,DaysOnMarket,price_per_sqft,close_to_original_list_ratio
count,2.900000e+02,1152.00000,290.000000,285.000000
mean,1.416594e+06,17.46441,912.092821,1.060067
std,4.725417e+05,25.66652,209.412561,0.092444
min,5.000000e+05,0.00000,460.000000,0.764277
25%,1.136250e+06,7.00000,748.794308,1.000000
50%,1.388050e+06,12.00000,856.485431,1.047619
75%,1.634583e+06,20.00000,1025.666760,1.116059
max,4.005000e+06,433.00000,1550.751880,1.402806

In [34]:
list_flagged_mp['year'] = pd.to_datetime(list_flagged_mp['year_month']).dt.year
list_flagged_mp.groupby('year')['ClosePrice'].median()

C:\Users\User\AppData\Local\Temp\ipykernel_3796\3191803106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  list_flagged_mp['year'] = pd.to_datetime(list_flagged_mp['year_month']).dt.year

year
2024    1467500.5
2025    1310000.0
2026    1260000.0
Name: ClosePrice, dtype: float64

In [44]:
list_flagged_mp.groupby('year')['DaysOnMarket'].mean()

year
2024    14.414487
2025    18.223496
2026    21.552288
Name: DaysOnMarket, dtype: float64

In [45]:
list_flagged_mp.groupby('year')['close_to_original_list_ratio'].mean()

year
2024    1.099032
2025    1.031180
2026    1.015724
Name: close_to_original_list_ratio, dtype: float64

In [35]:
list_flagged_mp.groupby('year')['ListingId'].nunique()

year
2024    497
2025    349
2026    306
Name: ListingId, dtype: int64

In [42]:
list_flagged_mp.groupby('year')['ClosePrice'].sum()

year
2024    203994380.0
2025    128457100.0
2026     78360638.0
Name: ClosePrice, dtype: float64

In [37]:
list_flagged_mp['ListAgentFullName'].value_counts()

ListAgentFullName
Erica Wong            95
Bernadina Romero      31
Debbie I. Giordano    27
Sophie Shen           26
Kashif Husain         21
                      ..
Jaswinder Gill         1
Yolanda Zhang          1
Lucia Liu              1
Renuka Bharti          1
Joseph Rondone         1
Name: count, Length: 650, dtype: int64

In [38]:
list_flagged_mp.groupby('ListAgentFullName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListAgentFullName
Erica Wong            38689187.0
Sophie Shen           15460500.0
Debbie I. Giordano     8427333.0
David Azimi            7910000.0
Annie Culbertson       7573134.0
Name: ClosePrice, dtype: float64

In [39]:
list_flagged_mp['ListOfficeName'].value_counts()

ListOfficeName
Intero Real Estate Services    115
Coldwell Banker Realty         103
168 Realty                      95
Compass                         91
Keller Williams Thrive          45
                              ...
H2D Realty                       1
Good Neighbor Realty             1
Success Realty Inc               1
1st Choice Realty & Assoc        1
Maremonte Realty Inc             1
Name: count, Length: 255, dtype: int64

In [40]:
list_flagged_mp.groupby('ListOfficeName')['ClosePrice'].sum().sort_values(ascending = False).head()

ListOfficeName
Intero Real Estate Services    47652801.0
Coldwell Banker Realty         46052776.0
Compass                        43352890.0
168 Realty                     38689187.0
Keller Williams Thrive         20910500.0
Name: ClosePrice, dtype: float64